### ISSUE TITLE
Remove product from cart is not updating projection

### ISSUE THREAD

**Issue by SamAllen83** [EventStore/samples#27]
Steps to reproduce
1. Import attached postman collection
2. Run CQRS_Flow/Java/event-sourcing-esdb-aggregates or CQRS_Flow/Java/event-sourcing-esdb-simple application locally
3. Send `1. Open Shopping Cart` Postman request.  This will store ETag and Location for future requests.
4. Send `2. Add Product To Cart` Postman request.  This will update stored ETag for future requests.
5. Send `3. Get Cart By Id` Postman request.  This will store productId and unitPrice for future requests.
    * Notice Shopping Cart has 1 product in productItems
7. Send `4. Remove Product From Cart` Postman request.  This will update stored ETag for future requests.
8. Send `3. Get Cart By Id` Postman request.

Expected Result
* Shopping Cart should have 0 products in productItems

Actual Result
* Shopping Cart has 1 product in productItems

Developer Note: I will submit a PR to fix.  The issue is this line of code:
```
view.getProductItems().remove(existingProductItem);
```
Should be
```
view.getProductItems().remove(existingProductItem.get());
```

existingProductItem is of type 'Optional<ShoppingCartDetailsProductItem>', need to call `.get()` to get ShoppingCartDetailsProductItem.

[event-sourcing-esdb-aggregates.postman_collection.json](https://github.com/EventStore/samples/files/13800345/event-sourcing-esdb-aggregates.postman_collection.json)

**Comment by josephcummings** [comment]
Closing as fixed in #28
